version: '3'

services:
  wrparker.me:
    image: php:apache
    volumes:
      - ./site:/var/www/html
    restart: always
    environment:
      VIRTUAL_HOST: wrparker.me
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: wrparker.me
      LETSENCRYPT_EMAIL: me@wrparker.me
networks:
  default:
    external:
      name: nginx-proxy
