version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./site:/var/www/html
    restart: always
    environment:
      VIRTUAL_HOST: hrrn.nmtechgroup.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: hrrn.nmtechgroup.com
      LETSENCRYPT_EMAIL: me@wrparker.me

    db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - hrrn_db:/var/lib/mysql
networks:
  default:
    external:
      name: nginx-proxy
