version: '3'

services:
  wrparker.me:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./site:/var/www/html
    restart: always
    environment:
      VIRTUAL_HOST: hrrn.nmtechgroup.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: hrrn.nmtechgroup.com
      LETSENCRYPT_EMAIL: me@wrparker.me
networks:
  default:
    external:
      name: nginx-proxy
