version: '3'

services:
  sneekxy_app:
    image: php:apache
    volumes:
      - ./site:/var/www/html
    restart: always
    environment:
      VIRTUAL_HOST: sneekxy.nmtechgroup.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: sneekxy.nmtechgroup.com
      LETSENCRYPT_EMAIL: me@wrparker.me

networks:
  default:
    external:
      name: nginx-proxy
