version: '3'

services:
  jessethomason_app:
    build:
      dockerfile: ./Dockerfile
      context: . 
    volumes:
      - ./site:/var/www/html
    restart: always
    environment:
      VIRTUAL_HOST: jessethomason.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: jessethomason.com
      LETSENCRYPT_EMAIL: me@wrparker.me
      HTTPS_METHOD: redirect

networks:
  default:
    external:
      name: nginx-proxy

