version: '3'

services:
  ihaveablognow_app:
    image: wordpress
    volumes:
      - ./site:/var/www/html
    restart: always
    environment:
      VIRTUAL_HOST: ihaveablognow.com,operationcognition.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ihaveablognow.com,operationcognition.com
      LETSENCRYPT_EMAIL: me@wrparker.me

networks:
  default:
    external:
      name: nginx-proxy
