version: '3'

services:
  tnfrw_app:
    image: wordpress
    volumes:
      - ./site:/var/www/html
    restart: always
    environment:
      VIRTUAL_HOST: tnfrw.org
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: tnfrw.org
      LETSENCRYPT_EMAIL: me@wrparker.me

  tnfrw_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - tnfrw_db:/var/lib/mysql

volumes:
  tnfrw_db:

networks:
  default:
    external:
      name: nginx-proxy
