version: '3'

services:
  tnfrw_app:
    image: wordpress
    volumes:
      - ./site:/var/www/html
    restart: always
    environment:
      VIRTUAL_HOST: tnfrw.org
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: tnfrw.org
      LETSENCRYPT_EMAIL: me@wrparker.me

networks:
  default:
    external:
      name: nginx-proxy

