version: '3'

services:
  rwop_app:
    image: wordpress
    volumes:
      - ./site:/var/www/html
    restart: always
    environment:
      VIRTUAL_HOST: rwop.org
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: rwop.org
      LETSENCRYPT_EMAIL: me@wrparker.me
      HTTPS_METHOD: redirect

networks:
  default:
    external:
      name: nginx-proxy

